spring.config.import=optional:classpath:secret.properties
spring.application.name=clothing-store-server
server.port=8080

# MongoDB Configuration
#spring.mongodb.uri=mongodb://localhost:27017/clothing_store
spring.mongodb.uri=mongodb+srv://lvhmod_db_user:haolang828@shopqa.phdqlah.mongodb.net/shopqa?appName=shopqa

# Google Gemini API
gemini.api.key=${my.gemini.key}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemma-3-12b-it:generateContent?key=

# Client ID and Secret (Mapped from secret.properties)
google.client.id=${my.google.client}
google.client.secret=${my.google.client.secret}

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${google.client.id}
spring.security.oauth2.client.registration.google.client-secret=${google.client.secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo